version: '3.4'

services:
  notesdb:
    image: mongo

  notes.api:
    image: ${DOCKER_REGISTRY-}notesapi
    build:
      context: .
      dockerfile: src/Services/Notes/Notes.API/Dockerfile

volumes:
  mongo_data: