version: '3.4'

services:
  notesdb:
    container_name: notesdb
    restart: always
    ports:
       - "27017:27017"
    volumes:
       - mongo_data:/data/db

  notes.api:
    container_name: notes.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NotesDatabaseSettings:ConnectionString=mongodb://notesdb:27017
    depends_on:
     - notesdb
    ports:
      - "8000:80"